from mado.types_ import SCREEN_ID, VIRTUAL_DESKTOP_ID

VIRTUAL_DESKTOP_IDS = [
    VIRTUAL_DESKTOP_ID(1),  # Editor
    VIRTUAL_DESKTOP_ID(4),  # Music
    VIRTUAL_DESKTOP_ID(2),  # Terminal
    VIRTUAL_DESKTOP_ID(3),  # Browser
    VIRTUAL_DESKTOP_ID(5),  # Misc
]

PREFIX = "<f24>"

TOP_SCREEN_ID = SCREEN_ID("TOP")
LEFT_SCREEN_ID = SCREEN_ID("LEFT")
RIGHT_SCREEN_ID = SCREEN_ID("RIGHT")
MID_SCREEN_ID = SCREEN_ID("MID")

SCREEN_IDS = [
    TOP_SCREEN_ID,
    LEFT_SCREEN_ID,
    RIGHT_SCREEN_ID,
    MID_SCREEN_ID,
]
SCREEN_REMOVAL_PRIORITY = [
    TOP_SCREEN_ID,
    RIGHT_SCREEN_ID,
    LEFT_SCREEN_ID,
]

INIT_FOCUSED_SCREEN_ID = MID_SCREEN_ID

IGNORED_WINDOW_TITLES = {
    "Task Switching",
    "Chrome Legacy Window",
}

MOUSE_FOLLOWS_FOCUS = True

DEFAULT_ORIGIN = (0, 0)
